### ISSUE TITLE
Rate Limited Tests Cases

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#101]
<a href="https://github.com/dontirun"><img src="https://avatars2.githubusercontent.com/u/4570879?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dontirun](https://github.com/dontirun)**
_Thursday May 03, 2018 at 15:53 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/26_

----

Submitting too may test cases gets rate limited by Lex

Example:

LimitExceededException: You are sending requests at an excessive rate for $LATEST version of a bot. The $LATEST version of your bot should only be used for manual testing while building the bot. Amazon Lex limits the number of runtime requests that you can make to the $LATEST version of the bot. If you need to test or use the bot for higher request volume we recommend that you create a numeric version for the bot.
    at Object.extractError (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/home/ec2-user/git/aws-ai-qna-bot-2/node_modules/aws-sdk/lib/event_listeners.js:269:13)
    at emitNone (events.js:111:20)

**Comment by JohnCalhoun** [comment]
fixed in 2.1.0
