### ISSUE TITLE
Building from Source: Creating Question Results in Errors

### ISSUE THREAD

**Issue by jfischburg-lifemesh** [aws-samples/aws-ai-qna-bot#282]
Hello,

After building the solution from source and deploying, we aren't able to submit questions via the web interface.

The following images exhibit:
1. 9.35.00 Screen Shot: Creation of a question in the web interface
2. 9.35.10 Screen Shot: Error Code received
<img width="845" alt="Screen Shot 2021-07-14 at 09 35 00" src="https://user-images.githubusercontent.com/56294903/125660453-a245df6c-e7a6-438f-b6b4-af28c331087c.png">
<img width="1638" alt="Screen Shot 2021-07-14 at 09 35 10" src="https://user-images.githubusercontent.com/56294903/125660454-d736dad0-665a-4745-b20f-a5ca6c0c953d.png">

main.js:28 [Vue warn]: Error in created hook: "TypeError: this.$store.dispatch(...).then(...).then(...).tapCatch is not a function"

found in

---> <Loading> at js/components/loading.vue
       <VApp>
         <Admin> at js/admin.vue
           <Root>
pe @ main.js:28

main.js:28 TypeError: this.$store.dispatch(...).then(...).then(...).tapCatch is not a function
    at o.created (main.js:30)
    at it (main.js:28)
    at Cr (main.js:28)
    at o.t._init (main.js:28)
    at new o (main.js:28)
    at main.js:28
    at init (main.js:28)
    at r (main.js:28)
    at main.js:28
    at h (main.js:28)
    at b (main.js:28)
    at h (main.js:28)
    at b (main.js:28)
    at h (main.js:28)
    at b (main.js:28)
    at h (main.js:28)
ot @ main.js:28

main.js:28 [Vue warn]: Error in created hook: "TypeError: a(...).then(...).then(...).spread is not a function"

found in

---> <Alexa> at js/components/designer/alexa.vue
       <VListTile>
         <VList>
           <VMenu>
             <VCard>
               <Index> at js/components/designer/index.vue
                 <VApp>
                   <Admin> at js/admin.vue
                     <Root>
pe @ main.js:28

TypeError: a(...).then(...).then(...).spread is not a function
    at l.botinfo (main.js:77)
    at Array.<anonymous> (main.js:16)
    at l.dispatch (main.js:22)
    at l.dispatch (main.js:16)
    at o.created (main.js:30)
    at it (main.js:28)
    at Cr (main.js:28)
    at o.t._init (main.js:28)
    at new o (main.js:28)
    at main.js:28
    at init (main.js:28)
    at main.js:28
    at h (main.js:28)
    at b (main.js:28)
    at h (main.js:28)
    at b (main.js:28)
ot @ main.js:28

main.js:28 [Vue warn]: Error in created hook (Promise/async): "TypeError: a(...).tap is not a function"

found in

---> <Index> at js/components/designer/index.vue
       <VApp>
         <Admin> at js/admin.vue
           <Root>
pe @ main.js:28

main.js:28 TypeError: a(...).tap is not a function
    at l.get (main.js:77)
    at Array.<anonymous> (main.js:16)
    at l.dispatch (main.js:22)
    at l.dispatch (main.js:16)
    at o.<anonymous> (main.js:30)
    at y (main.js:30)
    at Generator._invoke (main.js:30)
    at Generator.S.forEach.e.<computed> [as next] (main.js:30)
    at n (main.js:30)
    at main.js:30
    at P.r._execute (main.js:8)
    at P._resolveFromExecutor (main.js:8)
    at new P (main.js:8)
    at o.<anonymous> (main.js:30)
    at o.<anonymous> (main.js:30)
    at h (main.js:16)
ot @ main.js:28

PROXY LAMBDA
2021-07-14T15:19:16.278Z	cbfd65b7-40e0-42e4-8467-f1650ae4438d	INFO	error is {
    "message": "Request failed with status code 404",
    "name": "Error",
    "stack": "Error: Request failed with status code 404\n    at createError (/opt/nodejs/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/nodejs/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/opt/nodejs/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)",
    "config": {
        "url": "https://[redacted/ADMIN.001 ",
        "method": "head",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Host": "[redacted]",
            "X-Amz-Security-Token": "[redacted]",
            "X-Amz-Date": "20210714T151916Z",
            "Authorization": "AWS4-HMAC-SHA256 Credential=XXXXXXXX/, SignedHeaders=host;x-amz-date;x-amz-security-token, Signature=[redacted]",
            "User-Agent": "axios/0.21.1"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "host": "search-qna-xxxxx..es.amazonaws.com",
        "path": "/qna-live-dev-master-1/_all/ADMIN.001"
    }
}

2021-07-14T15:19:16.278Z	cbfd65b7-40e0-42e4-8467-f1650ae4438d	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "{\"type\":\"[NotFound]\",\"status\":404,\"message\":\"Not Found\",\"data\":\"\"}",
    "stack": [
        "Error: {\"type\":\"[NotFound]\",\"status\":404,\"message\":\"Not Found\",\"data\":\"\"}",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)",
        "    at postError (/var/runtime/CallbackContext.js:29:54)",
        "    at callback (/var/runtime/CallbackContext.js:41:7)",
        "    at /var/runtime/CallbackContext.js:106:16",
        "    at Runtime.module.exports [as handler] (/opt/lib/handler.js:162:16)"
    ]
}

 
FROM ELASTICSEARCH WARMER:

2021-07-14T15:19:34.345Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'lodash'\nRequire stack:\n- /var/task/lib/router/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lodash'",
        "Require stack:",
        "- /var/task/lib/router/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

Unknown application error occurred
Runtime.ImportModuleError

**Comment by jfischburg-lifemesh** [comment]
Issue related to build environment. We have resolved.
